[versions]
androidGradlePlugin = "8.13.1"
coil = "2.7.0"
constraintlayoutCompose = "1.1.1"
composeCompiler = "1.5.15"
glide = "5.0.5"
hilt = "2.57.2"
kotlin = "2.2.21"
kotlinxCoroutinesAndroid = "1.10.2"
kotlinxCoroutinesCore = "1.10.2"
ksp = "2.2.21-2.0.4"
googleMaterial = "1.13.0"
androidxActivity = "1.12.0"
androidxAnnotation = "1.9.1"
androidxAppCompat = "1.7.1"
androidxBrowser = "1.9.0"
androidxCardView = "1.0.0"
androidxConstraintlayout = "2.2.1"
androidxCoordinatorlayout = "1.3.0"
androidxCore = "1.17.0"
androidxCoreSplashscreen = "1.2.0"
androidxDataStore = "1.2.0"
androidxEspresso = "3.7.0"
androidxExifinterface = "1.4.1"
androidxFragment = "1.8.9"
androidxLifecycle = "2.10.0"
androidxLegacySupportV4 = "1.0.0"
androidxMacroBenchmark = "1.4.1"
androidxMultidex = "2.0.1"
androidxMetrics = "1.0.0"
androidxNavigation = "2.9.6"
androidxProfileinstaller = "1.4.1"
androidxRecyclerview = "1.4.0"
androidxStartup = "1.2.0"
androidxTestCore = "1.7.0"
androidxTestExt = "1.3.0"
androidxTestRules = "1.7.0"
androidxTestRunner = "1.7.0"
androidxTracing = "1.3.0"
androidxViewpager2 = "1.1.0"
androidxUiAutomator = "2.3.0"
androidxWindowManager = "1.5.1"
androidxMedia = "1.8.0"
androidxWork = "2.11.0"
activityCompose = "1.12.0"
junit4 = "4.13.2"
timber = "5.0.1"
room = "2.8.4"
androidxComposeBom = "2025.11.01"
mmkv = "2.2.4"

[libraries]
androidx-activity = { module = "androidx.activity:activity", version.ref = "androidxActivity" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "androidxActivity" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "androidxAnnotation" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidxAppCompat" }
androidx-benchmark-macro = { module = "androidx.benchmark:benchmark-macro-junit4", version.ref = "androidxMacroBenchmark" }
androidx-browser = { module = "androidx.browser:browser", version.ref = "androidxBrowser" }
androidx-cardview = { module = "androidx.cardview:cardview", version.ref = "androidxCardView" }
androidx-compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "composeCompiler" }
androidx-constraintlayout-core = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidxConstraintlayout" }
androidx-constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintlayoutCompose" }
androidx-coordinatorlayout = { module = "androidx.coordinatorlayout:coordinatorlayout", version.ref = "androidxCoordinatorlayout" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidxCore" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "androidxCoreSplashscreen" }
androidx-dataStore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "androidxDataStore" }
androidx-dataStore-preferences-rxjava2 = { module = "androidx.datastore:datastore-preferences-rxjava2", version.ref = "androidxDataStore" }
androidx-dataStore-preferences-rxjava3 = { module = "androidx.datastore:datastore-preferences-rxjava3", version.ref = "androidxDataStore" }
androidx-dataStore-proto = { module = "androidx.datastore:datastore", version.ref = "androidxDataStore" }
androidx-dataStore-proto-rxjava2 = { module = "androidx.datastore:datastore-rxjava2", version.ref = "androidxDataStore" }
androidx-dataStore-proto-rxjava3 = { module = "androidx.datastore:datastore-rxjava3", version.ref = "androidxDataStore" }
androidx-exifinterface = { module = "androidx.exifinterface:exifinterface", version.ref = "androidxExifinterface" }
androidx-fragment = { module = "androidx.fragment:fragment", version.ref = "androidxFragment" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "androidxFragment" }
androidx-junit-ext = { module = "androidx.test.ext:junit", version.ref = "androidxTestExt" }
androidx-lifecycle-common-java8 = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "androidxLifecycle" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidx-legacy-support-v4 = { module = "androidx.legacy:legacy-support-v4", version.ref = "androidxLegacySupportV4" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidxLifecycle" }
androidx-metrics = { module = "androidx.metrics:metrics-performance", version.ref = "androidxMetrics" }
androidx-multidex = { module = "androidx.multidex:multidex", version.ref = "androidxMultidex" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidxNavigation" }
androidx-navigation-testing = { module = "androidx.navigation:navigation-testing", version.ref = "androidxNavigation" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidxNavigation" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "androidxNavigation" }
androidx-navigation-dynamic-features-fragment = { module = "androidx.navigation:navigation-dynamic-features-fragment", version.ref = "androidxNavigation" }
androidx-profileinstaller = { module = "androidx.profileinstaller:profileinstaller", version.ref = "androidxProfileinstaller" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "androidxRecyclerview" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-testing = { module = "androidx.room:room-testing", version.ref = "room" }
androidx-test-core = { module = "androidx.test:core", version.ref = "androidxTestCore" }
androidx-test-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidxEspresso" }
androidx-test-ext = { module = "androidx.test.ext:junit-ktx", version.ref = "androidxTestExt" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidxTestRules" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidxTestRunner" }
androidx-test-uiautomator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "androidxUiAutomator" }
androidx-tracing-ktx = { module = "androidx.tracing:tracing-ktx", version.ref = "androidxTracing" }
androidx-viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "androidxViewpager2" }
androidx-window-manager = { module = "androidx.window:window", version.ref = "androidxWindowManager" }
androidx-work-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "androidxWork" }
androidx-work-testing = { module = "androidx.work:work-testing", version.ref = "androidxWork" }
androidx-media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref="androidxMedia" }
androidx-media3-exoplayer-dash = { module = "androidx.media3:media3-exoplayer-dash", version.ref="androidxMedia" }
androidx-media3-ui = { module = "androidx.media3:media3-ui", version.ref="androidxMedia" }
androidx-media3-session = { module = "androidx.media3:media3-session", version.ref="androidxMedia" }
coil = { module = "io.coil-kt:coil", version.ref = "coil" }
junit4 = { module = "junit:junit", version.ref = "junit4" }
glide-glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }
google-material = { module = "com.google.android.material:material", version.ref = "googleMaterial" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
tencent-mmkv = { module = "com.tencent:mmkv", version.ref = "mmkv"}
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber"}
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt"}
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt"}
androidx-startup-runtime = { module = "androidx.startup:startup-runtime", version.ref = "androidxStartup"}


activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
compose-compiler = { module = "org.jetbrains.kotlin:kotlin-compose-compiler-plugin-embeddable", version.ref = "kotlin" }
# compose-bom
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "androidxComposeBom" }
compose-animation = { module = "androidx.compose.animation:animation" }
compose-animation-core = { module = "androidx.compose.animation:animation-core" }
compose-animation-graphics = { module = "androidx.compose.animation:animation-graphics" }
compose-foundation = { module = "androidx.compose.foundation:foundation" }
compose-foundation-layout = { module = "androidx.compose.foundation:foundation-layout" }
compose-material = { module = "androidx.compose.material:material" }
compose-material-icons-core = { module = "androidx.compose.material:material-icons-core" }
compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
compose-material-ripple = { module = "androidx.compose.material:material-ripple" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-material3-window-size = { module = "androidx.compose.material3:material3-window-size-class" }
compose-runtime = { module = "androidx.compose.runtime:runtime" }
compose-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata" }
compose-runtime-rxjava2 = { module = "androidx.compose.runtime:runtime-rxjava2" }
compose-runtime-rxjava3 = { module = "androidx.compose.runtime:runtime-rxjava3" }
compose-runtime-saveable = { module = "androidx.compose.runtime:runtime-saveable" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-geometry = { module = "androidx.compose.ui:ui-geometry" }
compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
compose-ui-test = { module = "androidx.compose.ui:ui-test" }
compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
compose-ui-text = { module = "androidx.compose.ui:ui-text" }
compose-ui-text-google-fonts = { module = "androidx.compose.ui:ui-text-google-fonts" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-tooling-data = { module = "androidx.compose.ui:ui-tooling-data" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-ui-unit = { module = "androidx.compose.ui:ui-unit" }
compose-ui-util = { module = "androidx.compose.ui:ui-util" }
compose-ui-viewbinding = { module = "androidx.compose.ui:ui-viewbinding" }

[bundles]
androidx-media3 = [
    "androidx-media3-exoplayer",
    "androidx-media3-exoplayer-dash",
    "androidx-media3-ui",
    "androidx-media3-session"
]

compose = [
    "compose-animation",
    "compose-animation-core",
    "compose-animation-graphics",
    "compose-foundation",
    "compose-foundation-layout",
    "compose-material",
    "compose-material-icons-core",
    "compose-material-icons-extended",
    "compose-material-ripple",
    "compose-material3",
    "compose-material3-window-size",
    "compose-runtime",
    "compose-runtime-livedata",
    "compose-runtime-rxjava2",
    "compose-runtime-rxjava3",
    "compose-runtime-saveable",
    "compose-ui",
    "compose-ui-geometry",
    "compose-ui-graphics",
    "compose-ui-text",
    "compose-ui-text-google-fonts",
    "compose-ui-tooling",
    "compose-ui-tooling-data",
    "compose-ui-tooling-preview",
    "compose-ui-unit",
    "compose-ui-util",
    "compose-ui-viewbinding"
]

kotlinx-coroutines = [
    "kotlinx-coroutines-core",
    "kotlinx-coroutines-android"
]

test-compose = [
    "compose-ui-test",
    "compose-ui-test-junit4",
    "compose-ui-test-manifest",
]


[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
android-test = { id = "com.android.test", version.ref = "androidGradlePlugin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
navigation-safeargs = { id = "androidx.navigation.safeargs", version.ref = "androidxNavigation" }